### PR TITLE
Implement a native Angular events strategy for DevExtreme EventsMixin

### LINKED ISSUE #299: dxScrollView always shows wait indicator in an Angular 2 application
The Scroll View always shows the wait indicator. A sample project is attached
[tmp.zip](https://github.com/DevExpress/devextreme-angular/files/663606/tmp.zip)
mysnippet

### PR DESCRIPTION
**Pull request by ovchinnikov**
Fixes #299

### CODE REVIEW

**Comment by VladeKovacic** [comment]
I tried this change, and now do not work control events "dx-list" located within the "DX-scroll-view" or "dx-resizable" in which is the "DX-scroll-view".
In "dx-resizable" does not work event "onResize" and in "DX-list" does not work event "onSelectionChanged".


Throughout my application I noticed some problems with the drawing dxDataGrid that works fine with version "devextreme-angular@16.2.3-rc.3" but does not work correctly with the version of "devextreme-angular@16.2.3-rc.4".


Please give me information whether is this a big problem and when it expects a solution, or maybe I'm doing something wrong.

I cannot attach zip file with zip temp project. 
Error message: "We don’t support that file type.  Odabir datoteka Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP."

Best regards,
Vlade Kovačić.

rc3
rc4

**Comment by VladeKovacic** [comment]
I attach projects on devextreme ticket "https://www.devexpress.com/Support/Center/Question/Details/T463883"

**Comment by Aden-git** [comment]
Hello @VladeKovacic 

Please, try to update a devextreme package version to ~16.2.4-0 in your package.json file.

**Comment by VladeKovacic** [comment]
Now it is working, after I add "devextreme": "~16.2.4-0" in package.json.
Thanks for support.

**Pull request merged**
