### PR TITLE
Reset value of nested components

### PR DESCRIPTION
**Pull request by dxvladislavvolkov**

### CODE REVIEW

**Comment by hakimio** [comment]
@dxvladislavvolkov 
This fix causes the following error:
```
ERROR TypeError: Cannot read property 'resetOption' of undefined
    at DxoPagingComponent._resetOption (vendor.js:147523)
    at DxoPagingComponent.ngOnDestroy (vendor.js:201520)
    at callProviderLifecycles (vendor.js:67582)
    at callElementProvidersLifecycles (vendor.js:67541)
    at callLifecycleHooksChildrenFirst (vendor.js:67523)
    at destroyView (vendor.js:78623)
    at callViewAction (vendor.js:78782)
    at execComponentViewsAction (vendor.js:78690)
    at destroyView (vendor.js:78622)
    at callViewAction (vendor.js:78782)
```

Should be possible to reproduce with `devextreme-angular-template` app.

**Comment by dxvladislavvolkov** [comment]
@hakimio hi.
Can you provide steps to reproduce? I couldn't reproduce this issue on my side

**Comment by hakimio** [comment]
@dxvladislavvolkov I don't have the time to create a full demo, but you could try something like the following:
```html
<ng-container *ngIf="isAuthorized; else notAuthorized">
    <app-navigation>
        <div class="dx-card content-block responsive-paddings">
            <router-outlet></router-outlet>
        </div>
    </app-navigation>
</ng-container>

<ng-template #notAuthorized>
    <app-card>
        <router-outlet></router-outlet>
    </app-card>
</ng-template>
```

```ts
@Component({
    selector: 'app-root',
    templateUrl: './app.component.html',
    styleUrls: ['./app.component.scss']
})
export class AppComponent implements OnInit {

    isAuthorized: boolean;

    ngOnInit() {
        setTimeout(() => this.isAuthorized = true, 500);
    }
}
```

When `isAuthorized` is `false` Router should redirect to login component, otherwise it should redirect to a component which displays datagrid with paging toolbar. `app-navigation` is [this component](https://github.com/DevExpress/devextreme-angular-template/blob/master/src/app/layouts/side-nav-inner-toolbar/side-nav-inner-toolbar.component.ts).
If you still can't reproduce with this example I'll try to create a demo app for you sometime next week.

**Comment by hakimio** [comment]
@dxvladislavvolkov it seems we are not the only ones experiencing issues with this fix:
https://www.devexpress.com/Support/Center/Question/Details/T849449/cannot-read-property-resetoption-of-undefined

**Comment by onebalaban** [comment]
Hello,

We didn't manage to reproduce the issue. Could you please modify the project I attached to the [https://supportcenter.devexpress.com/ticket/details/T849449](https://supportcenter.devexpress.com/ticket/details/T849449) ticket to demonstrate the problem?

**Pull request merged**
